version: '3.8'
services:
  sqlserver:
    build: .
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Emmanuel142*"
    restart: always
